name: Testing
on: 
  workflow_dispatch:
    inputs:
      project_name:
        type: choice
        options:
          - boutique-dev
          - boa
      # environment:
      #   type: choice
      #   options:
      #     - 'non-prod'
      #     - 'prod'
        description: 'Project Name In GCP'
      terraform_options:
        type: choice
        options:
          - n/a
          - validate
          - plan
          - apply
          - destroy
          - outputs
jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Display Inputs
        run: |
          echo "Selected Environment is: ${{ github.event.inputs.environment}}"
          echo "Selected Command is: ${{ github.event.inputs.terraform_options}}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install jq
        run: sudo apt-get install jq
      - name: Read Project Configuration
        id: read_project_config
        run: |
          echo "Present Working Directory"
          pwd
          echo "Listing files"
          ls
          project_id=$(jq -r '.["${{ github.event.inputs.project }}"].project_id' project-config.json)
          echo "PROJECT_ID=${project_id}" >> $GITHUB_ENV
          echo "**************** Printing all Values ***********"
          echo $GITHUB_ENV